# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='gravatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
