# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0002_visit_gravatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceVisitEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycon.Conference')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycon.Visit')),
            ],
        ),
    ]
