# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0003_conferencevisitentry'),
        ('pycon', '0003_auto_20170216_0613'),
    ]

    operations = [
    ]
