# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0005_auto_20170216_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pycon.Conference'),
        ),
    ]
