# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0007_auto_20170216_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Delegate'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_left',
            field=models.DateTimeField(verbose_name='Departure Date'),
        ),
    ]
