version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./:/src
      - ./nginx/sites-enabled:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "gunicorn Pycon0217Namibia.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./:/src
    expose:
      - "8000"
